In [49]:
#import numba as nb
from numba import njit
import time

string = "12C"

def slow(x,number):
    for i1 in range(it):
        x += 1
        for i2 in range(it):
            x += 1
            for i3 in range(it):
                x += 1
                for i4 in range(it):
                    x += 1
                    for i5 in range(it):
                        x += 1
    print(x)

@njit
def fast(x,number):
    for i1 in range(it):
        x += 1
        for i2 in range(it):
            x += 1
            for i3 in range(it):
                x += 1
                for i4 in range(it):
                    x += 1
                    for i5 in range(it):
                        x += 1
    print(x)


def rec(x,number):
    print(loopThrough(x,number,1))
    

def loopThrough(x,number,y):
    for i in range(number):
        if y == 5:
            x+=1
        else:
            x= loopThrough(x+1,number,y+1)
    return x
    
@njit
def fastRec(x,number):
    print(fastLoopThrough(x,number,1))
    
@njit
def fastLoopThrough(x,number,y):
    for i in range(number):
        if y == 5:
            x+=1
        else:
            x= fastLoopThrough(x+1,number,y+1)
    return x    

it = 50

start = time.time()
slow(1,it)
print('normal:',time.time()-start)

start = time.time()
fast(1,it)
print('numba:',time.time()-start)

start = time.time()
rec(1,it)
print('recursion:',time.time()-start)

start = time.time()
fastRec(1,it)
print('numba recursion:',time.time()-start)

"""@njit
def product(*args, repeat=1):
    # product('ABCD', 'xy') --> Ax Ay Bx By Cx Cy Dx Dy
    # product(range(2), repeat=3) --> 000 001 010 011 100 101 110 111
    pools = [tuple(pool) for pool in args] * repeat
    result = [[]]
    for pool in pools:
        result = [x+[y] for x in result for y in pool]
    for prod in result:
        yield tuple(prod)"""

318877551
normal: 19.683952808380127
318877551
numba: 0.1035010814666748
318877551
recursion: 26.363401174545288
318877551
numba recursion: 0.2297060489654541


"@njit\ndef product(*args, repeat=1):\n    # product('ABCD', 'xy') --> Ax Ay Bx By Cx Cy Dx Dy\n    # product(range(2), repeat=3) --> 000 001 010 011 100 101 110 111\n    pools = [tuple(pool) for pool in args] * repeat\n    result = [[]]\n    for pool in pools:\n        result = [x+[y] for x in result for y in pool]\n    for prod in result:\n        yield tuple(prod)"

In [8]:
import re
print(re.findall('[A-Z][^A-Z]*', 'HO-3P1C5H5N5O1'))
formuladict = dict()
for item in re.findall('[A-Z][^A-Z]*', 'H1O-3P1C5H5N5O1'):
    match = re.match(r"([a-z]+)([0-9]+)", item, re.I)
    number = 1
    if match:
        number = int(match.group(2))
    
        if match.group(1) in formuladict:
            formuladict[match.group(1)] += number
        else:
            formuladict[match.group(1)] = number
    else:
        print("-" in item)
        print(item,item.find('-'))
for key,val in formuladict.items():
    print(key,val)

['H', 'O-3', 'P1', 'C5', 'H5', 'N5', 'O1']
True
O-3 1
H 6
P 1
C 5
N 5
O 1


In [33]:
from IPython.terminal.embed import InteractiveShellEmbed
ip_shell = InteractiveShellEmbed()
path = ip_shell.magic("%pwd")[:-17] + "/"
#path = ip_shell.magic("%pwd")[:-4] + "/"
monomerFile = path + 'Parameters/amino_acids.txt'

def removeEmptyElements(rawList):
    newList = rawList
    while '' in newList:
        newList.remove('')
    return newList

def stringToFormula(formulaString, formulaDict, sign):
    for item in re.findall('[A-Z][^A-Z]*', formulaString):
        element = item
        number = 1
        match = re.match(r"([a-z]+)([0-9]+)", item, re.I)
        if match:
            element = match.group(1)
            number = int(match.group(2))
        if element in formulaDict:
            formulaDict[element] += number * sign
        else:
            formulaDict[element] = number * sign
    return formulaDict

monomerDict = dict()
with open(monomerFile) as f:
    for line in f:
        if line.startswith('#') or line == "":
            continue
        lineList = removeEmptyElements(line.rstrip().split('\t'))
        monomerDict[lineList[0]] = stringToFormula(lineList[1],dict(),1)
for key,val in monomerDict.items():
    print(key,val)

A {'C': 3, 'H': 5, 'N': 1, 'O': 1}
R {'C': 6, 'H': 12, 'N': 4, 'O': 1}
N {'C': 4, 'H': 6, 'N': 2, 'O': 2}
D {'C': 4, 'H': 5, 'N': 1, 'O': 3}
C {'C': 3, 'H': 5, 'N': 1, 'O': 1, 'S': 1}
E {'C': 5, 'H': 7, 'N': 1, 'O': 3}
Q {'C': 5, 'H': 8, 'N': 2, 'O': 2}
G {'C': 2, 'H': 3, 'N': 1, 'O': 1}
H {'C': 6, 'H': 7, 'N': 3, 'O': 1}
O {'C': 5, 'H': 7, 'N': 1, 'O': 2}
I {'C': 6, 'H': 11, 'N': 1, 'O': 1}
L {'C': 6, 'H': 11, 'N': 1, 'O': 1}
K {'C': 6, 'H': 12, 'N': 2, 'O': 1}
M {'C': 5, 'H': 9, 'N': 1, 'O': 1, 'S': 1}
F {'C': 9, 'H': 9, 'N': 1, 'O': 1}
P {'C': 5, 'H': 7, 'N': 1, 'O': 1}
U {'C': 5, 'H': 5, 'N': 1, 'O': 2}
S {'C': 3, 'H': 5, 'N': 1, 'O': 2}
T {'C': 4, 'H': 7, 'N': 1, 'O': 2}
W {'C': 11, 'H': 10, 'N': 2, 'O': 1}
Y {'C': 9, 'H': 9, 'N': 1, 'O': 2}
V {'C': 5, 'H': 9, 'N': 1, 'O': 1}


In [35]:
import numpy as np
from scipy.stats import binom
from scipy.stats import multinomial
from math import factorial as fac

a = np.array([[1,0.5],[2,0.3]])
print(np.multiply(a[0,:],a[1,:]))


p=0.2
n=100
k=5
print(binom.pmf(k,n,p))

def binomial(n, k):
    try:
        binom = fac(n) / (fac(k) * fac(n - k))
    except ValueError:
        binom = 0
    return binom


print(binomial(n, k)*p**k*(1-p)**(n-k))

n = 100
k1 = 2
k2 = 3
p1 = 0.05
p2 = 0.1

n = 100
k1 = 2
k2 = 3
p1 = 0.05
p2 = 0.1


print(multinomial.pmf([n - k1-k2,k1, k2],n=n,p=[1-p1-p2,p1, p2]))


print(fac(n)/(fac(k1)*fac(k2)*fac(n-k1-k2))*p1**k1*p2**k2*(1-p1-p2)**(n-k1-k2))


#print(binom.pmf(0,9,0.1))
#print(sum(np.random.binomial(9,0.1,2000000)==0)/2000000)

[2.   0.15]
1.4976893243067188e-05
1.4976893243066699e-05
0.00037107435657551656
0.0003710743565754993


In [6]:
from numba import njit
from numba import jit
import math
import numpy as np
from scipy.stats import binom


"""@njit
def binomcoeff(n,k):
    i = n
    while True:
    #for i1 in reversed(range(n+1)):
        if i%(n-k) ==0:
            #print(i)
            break
        i -= 1
    number = 1
    for i2 in range(i,n+1):
        #print(i2,number)
        number*=i2
    numerator = 1
    for i3 in range(1,k):
        numerator *= i3
        print(i3,numerator)
    number /= numerator
    print(number)
    return number"""

@njit
def binomcoeff(n,k):
    print(fact(k))
    return math.exp(fact(n)-fact(k)-fact(n-k))

@njit
def fact(x):
    log_number = 0
    for i in range(1,x+1):
        log_number += math.log(i)
    return log_number



@njit
def binomial(k,n,p):
    return binomcoeff(n,k)*p**k*(1-p)**(n-k)

@njit
def multinomial(k0, k1, k2, n, p0, p1,p2):
    try:
        return (fact(n)/(fact(k1)*fact(k2)*fact(k0)) * p1**k1 * p2**k2 * (p0)**(k0))
    except ValueError:
        print(ValueError)
        return 0
#print(fact(100))
print(binomial(23,100,0.1))
print(binom.pmf(23,100,0.1))






l = [((1,2,3),(4,5,6)),(5,8,9)]

@njit
def a(liste):
    print(len(liste))
    for i in liste:
        for ii in i:
            print(ii)

print(list(range(10)[::-1]))
            
@njit
def b(x):
    for i in list(range(x))[::-1]:
        print(i)
b(10)

l = [(1,20,30),(1,20,35),(1,20,29),(2,30,50),(3,15,55)]
print(sorted(l,key= lambda tup:tup[1]))

isotopeTable = (5,4,3,2)

isotopeTable = np.array(isotopeTable, dtype=[('elem','U8'),('nrElem',np.uint32),('M+',np.uint8),('nrIso',np.uint8)])

arr = np.array([[1,2,3],[4,5,6]])


@njit
def exchange(x,y):
    for i in range(len(x)):
        x[i][2] =y[i]
    l = [(1,20,30),(1,20,35),(1,20,29),(2,30,50),(3,15,55)]
    b = np.array(l)
    return x
exchange(arr, np.array([7,8]))

arr -= 1
print(arr)
#a = np.concatenate((arr,np.array([7,8,9])),axis=0)
print(np.zeros((39,3)))


51.60667556776438
7.45188958938653e-05
7.451889589385675e-05
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
9
8
7
6
5
4
3
2
1
0
[(3, 15, 55), (1, 20, 30), (1, 20, 35), (1, 20, 29), (2, 30, 50)]
[[0 1 6]
 [3 4 7]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
from  __init__ import path
import xlrd
import numpy as np

print(path)
file = path+'Spectral_data/0707_10sb_moreNoise_out.xlsx'

workbook = xlrd.open_workbook(file)
#workbook = xlrd.open_workbook('C:\\Users\\atheelm\\Documents\\python excel mission\\errors1.xlsx', on_demand = True)
worksheet = workbook.sheet_by_index(0)
first_row = [] # The row where we stock the name of the column
#for col in range(worksheet.ncols):
    #print(worksheet.cell_value(0,col))
    #first_row.append( worksheet.cell_value(0,col) )
# tronsform the workbook to a list of dictionnary
data =[]
sequence = list()
for row in range(20, 59):
    rowList = list()
    for col in range(3):
        if worksheet.cell_value(row,col) == "":
            rowList.append(None)
        else:
            rowList.append(worksheet.cell_value(row,col))
    data.append(tuple(rowList))
    if row!=19:
        sequence.append(worksheet.cell_value(row,4))
    #print(row)
    #if row[1] != '-' and row[2] != '-':
        #data.append((int(row[0]),float(row[1]),float(row[2])))
    #elif row[1] != '-':
        #data.append((int(row[0]),float(row[1]),None))
    #elif row[2] != '-':
        #data.append((int(row[0]),None,float(row[2])))
    #elm = {}
    #for col in range(worksheet.ncols):
        #print(worksheet.cell_value(row,col))
        #elm[first_row[col]]=worksheet.cell_value(row,col)
    #data.append(elm)
#print(data)
data = np.array(data, dtype= np.float64)
"""for row in range(len(data)):
    if data[row][2] != None:
        data[row][2] = 1 - data[row,2]"""
for row in data:
    print(row)
#print(sequence)

/Users/eva-maria/Data_exchange_folder/new_FTMS-Scanner/FTMS_Scanner_3_3/
[ 1. nan nan]
[2.         0.         0.93764577]
[3.         0.         0.87537523]
[4.         0.         0.08307849]
[5.         0.02747519 0.97178848]
[6. 0. 1.]
[7.        0.        0.9755618]
[8.         0.         0.24056131]
[9. 0. 1.]
[10.          0.          0.90936584]
[11.          0.26660621  0.86795157]
[12.          0.          0.61724934]
[13.          0.09293004  0.92907297]
[14.          0.05477377  0.94935115]
[15.          0.          0.87481047]
[16.          0.0870394   0.50263182]
[17.          0.07715951  0.79219574]
[18.          0.          0.85690896]
[19.          0.13857698  0.82625631]
[20.          0.40971492  0.33843416]
[21.          0.49390047  0.4539404 ]
[22.          0.53565155  0.53544336]
[23.          0.5325246   0.47860658]
[24.          0.30389939  0.2710772 ]
[25.          0.71654803  0.35286751]
[26.          0.7500495   0.35755553]
[27.          0.58070031  0.30004389]


In [17]:
import xlsxwriter

workbook = xlsxwriter.Workbook('chart_line.xlsx')
worksheet = workbook.add_worksheet()
bold = workbook.add_format({'bold': 1})

# Add the worksheet data that the charts will refer to.
headings = ['sequence', 'c-fragm.', 'y-fragm.']

worksheet.write_row('A1', headings, bold)
row = 1
for i in data:
    col = 0
    for val in i:
        if not np.isnan(val):
            worksheet.write(row, col, val)
        col+=1
    row+=1
worksheet.write_column('D2', sequence)
# Create a new chart object. In this case an embedded chart.
chart1 = workbook.add_chart({'type': 'line'})

# Configure the first series.

custom_label = list()
#for i in sequence:
    #custom_label.append({'value':i})
custom_label = [{'value': 'G'}, {'value': 'G'}, {'value': 'U'}, {'value': 'C'}, {'value': 'U'}, {'value': 'G'}, {'value': 'G'}, {'value': 'G'}, {'value': 'C'}, {'value': 'G'}, {'value': 'C'}, {'value': 'A'}, {'value': 'G'}, {'value': 'C'}, {'value': 'G'}, {'value': 'U'}, {'value': 'C'}, {'value': 'A'}, {'value': 'A'}, {'value': 'U'}, {'value': 'G'}, {'value': 'A'}, {'value': 'C'}, {'value': 'G'}, {'value': 'C'}, {'value': 'U'}, {'value': 'G'}, {'value': 'A'}, {'value': 'C'}, {'value': 'G'}, {'value': 'G'}, {'value': 'U'}, {'value': 'A'}, {'value': 'C'}, {'value': 'A'}, {'value': 'G'}, {'value': 'G'}, {'value': 'C'}, {'value': 'C'}]


chart1.add_series({
    'name':       ['Sheet1', 0, 1],
    'categories': ['Sheet1', 1, 0, len(data), 0],
    'values':     ['Sheet1', 1, 1, len(data), 1],
    'marker':{'type':'automatic','size':4},
    'line': {'width': 2.5},
    'data_labels': {'value': True, 'custom': custom_label},
})

# Configure a second series. Note use of alternative syntax to define ranges.
#row0,col0 - row1,col1
chart1.add_series({
    'name':       ['Sheet1', 0, 2],
    'categories': ['Sheet1', 1, 0, len(data), 0],
    'values':     ['Sheet1', 1, 2, len(data), 2],
    'y2_axis':1,
    'marker':{'type':'automatic','size':4},
    'line': {'width': 2.5},
    'data_labels': {'value': True, 'custom': custom_label},
})
chart1.set_size({'width': len(data)*20+100, 'height': 400})
# Add a chart title and some axis labels.
chart1.set_title ({'name': 'Results'})
chart1.set_x_axis({'name': 'Sequence',
                   'name_font': {'size': 13},
                  'position_axis': 'on_tick',
                  'num_font':  {'size': 10},})
chart1.set_y_axis({'name': '5\'-O /%',
                   'name_font': {'size': 13},
                  'min': 0, 'max': 1,
                  'num_font':  {'size': 10},})
chart1.set_y2_axis({'name': '3\'-O /%',
                   'name_font': {'size': 13},
                  'min': 0, 'max': 1,
                  'num_font':  {'size': 10},
                   'reverse': True,
                   })
chart1.set_legend({'font': {'size': 12}})
print(custom_label)
# Set an Excel chart style. Colors with white outline and shadow.
chart1.set_style(10)

# Insert the chart into the worksheet (with an offset).
worksheet.insert_chart('D2', chart1, {'x_offset': 25, 'y_offset': 10})



# Add the worksheet data to be plotted.
data = [10, 40, 50, 20, 10, 50]
worksheet.write_column('E1', data)

# Create a new chart object.
chart2 = workbook.add_chart({'type': 'line'})

custom_labels = [
    {'value': 'Jan'},
    {'value': 'Feb'},
    {'value': 'Mar'},
    {'value': 'Apr'},
    {'value': 'May'},
    {'value': 'Jun'},
]

chart2.add_series({
    'values': '=Sheet1!$E$1:$E$6',
    'data_labels': {'value': True, 'custom': custom_labels},
})

worksheet.insert_chart('C1', chart2)



workbook.close()

[{'value': 'G'}, {'value': 'G'}, {'value': 'U'}, {'value': 'C'}, {'value': 'U'}, {'value': 'G'}, {'value': 'G'}, {'value': 'G'}, {'value': 'C'}, {'value': 'G'}, {'value': 'C'}, {'value': 'A'}, {'value': 'G'}, {'value': 'C'}, {'value': 'G'}, {'value': 'U'}, {'value': 'C'}, {'value': 'A'}, {'value': 'A'}, {'value': 'U'}, {'value': 'G'}, {'value': 'A'}, {'value': 'C'}, {'value': 'G'}, {'value': 'C'}, {'value': 'U'}, {'value': 'G'}, {'value': 'A'}, {'value': 'C'}, {'value': 'G'}, {'value': 'G'}, {'value': 'U'}, {'value': 'A'}, {'value': 'C'}, {'value': 'A'}, {'value': 'G'}, {'value': 'G'}, {'value': 'C'}, {'value': 'C'}]


In [8]:
from scipy.optimize import minimize
import numpy as np
#(peaks: 1Darray wie x)
# coeff 2D array: len(peaks),len(x)+1

def fun_sum_square(x, equ_matrix):
    sum_square = 0
    for i in range(len(equ_matrix)):
        square = equ_matrix[i][-1]
        for j in range(len(x)):
            square -= equ_matrix[i][j]*x[j]
        sum_square += square**2
    return sum_square
    #return 3.0266052993172e+15*x[0] + 52614331802797.9*x[1] - 3.0711296254221e+15

matrix_c14 = np.array([[13230668.5734686,0,16101981.0],
[22782917.613623, 0, 23878702.0],
[22199058.4857634, 0, 22013436.0],
[15707327.8158656, 0, 14660551.0],
[0, 3523514.64483478,6992482.0],
[8925938.55004, 2947271.67948978,6670750.0]])

    
initial_guess = np.array([1,1])
solution = minimize(fun_sum_square,initial_guess, matrix_c14)    
print(solution)
print(solution.x[1])
print(solution.fun**(1/2)/(4.03*10**6))

      fun: 49216293126872.97
 hess_inv: array([[ 3.37253182e-16, -4.14991918e-16],
       [-4.14991918e-16,  2.42276563e-14]])
      jac: array([0., 0.])
  message: 'Optimization terminated successfully.'
     nfev: 45
      nit: 5
     njev: 15
   status: 0
  success: True
        x: array([0.99988675, 0.85275371])
0.8527537140776039
1.740802108558917


In [12]:
from numba.typed import List

"""a = List(((3,4)))
a.append((5,6))
print(a)"""
set1 = {'a','b'}
set2 = {'a','b'}
print(set1-set2)
print(len(set1-set2))
print(len('AQSSNSTHEPLEVLKEETVNRHRAIVSVMEELEAVDWYDQRVDASTDPELTAILAHNRDEEKEHAAMTLEWLRRNDAKWAEHLRTYLFTEGPITAANSSSVDKLAAALEHHHHHH'))

set()
0
115


In [22]:
import math
from numba import njit
import numpy as np

@njit
def logFact(x):
    log_number = 0
    for i in range(1,x+1):
        log_number += math.log(i)
    return log_number

@njit
def multinomialOld(k0, k1, k2, n, p0, p1,p2):
    return math.exp(logFact(n)-(logFact(k1)+logFact(k2)+logFact(k0))) * p1**k1 * p2**k2 * (p0)**(k0)
@njit
def multinomial(k, n, p):
    coeff = logFact(n)
    rest = 1
    for i in range(len(k)):
        coeff -= logFact(k[i])
        rest *= p[i]**k[i]
    return math.exp(coeff) * rest

print(multinomialOld(970,10,20,1000,0.98,0.005,0.015),multinomial(k=np.array([970,10,20]),n=1000,p=np.array([0.98,0.005,0.015])))

0.0007313534503598594 0.0007313534503598594


In [15]:
import re
d = {'+ab':0.5,'+ac':1,'+ab+ac':1.5}
for mod1 in d.keys():
    for item in re.split('\+', mod1):
        if ('+'+item) in d.keys() and ('+'+item) != mod1:
            d[mod1] -= d['+'+item]
for key,val in d.items():
    print(key,val)

mod = '+10CMCT'
print(mod[mod.find('CMCT')-1])
match = re.match(r"([a-z]+)([0-9]+)", mod, re.I)
print(match)
print(re.findall(r"(\d+)"+'CMCT', mod))

mod = 'ab05+5CMCT+3NMIA'
print(re.findall(r"([a-z]+)([0-9]+)", mod))
print(re.findall(r"([a-z]+)", mod))
print(int(re.findall(r"([0-9]+)", mod)[0]))

+ab 0.5
+ac 1
+ab+ac 0.0
0
None
['10']
[('ab', '05')]
['ab']
5
5


In [13]:
import numpy as np
a = np.array([-0.08735718, 0.74677256, 0.65931742])
print(len(a))


dim = 3

minCharge = 8
maxCharge = 16

arr = np.zeros((maxCharge-minCharge+1,3))
for i in range(maxCharge-minCharge+1):
    arr[i][0]= minCharge+i
arr[13-minCharge][2] = 100
arr[2] =[5.,3,2]
print(arr)

Fe = [ [54,   -2,      53.9396089953,      0.0584535],
             [56,   2,      55.9349363349,      0.9175436],
             [57,   3,      56.9353928449,      0.0211910]]
print(np.array(Fe)[:,3])
val = np.array(Fe)
print(np.max(val[:,3]))
print(val[np.where(val[:,3] == np.max(val[:,3]))][0][2])

3
[[  8.   0.   0.]
 [  9.   0.   0.]
 [  5.   3.   2.]
 [ 11.   0.   0.]
 [ 12.   0.   0.]
 [ 13.   0. 100.]
 [ 14.   0.   0.]
 [ 15.   0.   0.]
 [ 16.   0.   0.]]
[0.0584535 0.9175436 0.021191 ]
0.9175436
55.9349363349


In [1]:
d = {"": 2, "k": 3}
print(d[""])

2


In [4]:
import xlsxwriter


workbook = xlsxwriter.Workbook('file.xlsx')
worksheet1 = workbook.add_worksheet('analysis')
worksheet2 = workbook.add_worksheet('ions')
del worksheet2
workbook.close()